### ISSUE TITLE
Example on using this with yew?

### ISSUE THREAD

**Issue by thedodd** [rise-ui/jss-rs#5]
Awesome work on this project. I was hoping to find a project already started for this. 

Any ideas on how to use this with Yew? I’ll experiment with it today.

**Comment by friktor** [comment]
@thedodd Hi) This project is developed primarily for use on the desktop - it's a complete system of working with raw styles - simular to jss. The essence of this project is not only in the style parsing - but also with the presentation of all the necessary self-sufficient api for working with styles from gui in runtime (layout, apperance, runtime middlewares - the project is written as part of the gui library). It has too many dependencies incompatible with wasm (yew including), and working with styles or DOM through wasm is inefficient in a modern web. 
🤘🏻🧐
